[client]
# Hide the default sidebar page navigation
# This will prevent the automatic display of pages/ directory navigation
showSidebarNavigation = false

# Optional: Hide error details for cleaner production look
showErrorDetails = "none"

# Optional: Set toolbar mode (you might want "minimal" or "viewer" for production)
toolbarMode = "auto"